# Generated by Django 4.2.7 on 2026-02-02 06:24

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_keywords_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_type', models.CharField(choices=[('flavor', 'Sabor'), ('size', 'Tamaño'), ('presentation', 'Presentación'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Tipo de Variación')),
                ('name', models.CharField(help_text='Ej: Sabor, Tamaño, Presentación', max_length=100, verbose_name='Nombre de la Variación')),
                ('value', models.CharField(help_text='Ej: Fresa, Grande, Botella 500ml', max_length=100, verbose_name='Valor')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio adicional (positivo) o descuento (negativo). Dejar en 0 para usar precio base.', max_digits=10, verbose_name='Modificador de Precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('sku', models.CharField(blank=True, help_text='Código único del producto', max_length=50, unique=True, verbose_name='SKU')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variations/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Variación de Producto',
                'verbose_name_plural': 'Variaciones de Productos',
                'ordering': ['variation_type', 'value'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Puedes usar formato de texto enriquecido: negrita, cursiva, listas, etc.', verbose_name='Descripción'),
        ),
        migrations.CreateModel(
            name='ProductVariationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/variations/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('is_primary', models.BooleanField(default=False, help_text='Marcar como imagen principal de la variación', verbose_name='Imagen Principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.productvariation', verbose_name='Variación')),
            ],
            options={
                'verbose_name': 'Imagen de Variación',
                'verbose_name_plural': 'Imágenes de Variaciones',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='store.product', verbose_name='Producto'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'variation_type', 'value')},
        ),
    ]
