# Generated by Django 4.2.7 on 2026-02-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productvariation_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='general_characteristics',
            field=models.TextField(blank=True, help_text='Información adicional del producto (peso, dimensiones, ingredientes, etc.)', verbose_name='Características Generales'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_type',
            field=models.CharField(blank=True, choices=[('bolsa', 'Bolsa'), ('caja', 'Caja'), ('botella', 'Botella'), ('lata', 'Lata'), ('sobre', 'Sobre'), ('frasco', 'Frasco'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Empaque'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_refrigeration_after_open',
            field=models.BooleanField(default=False, verbose_name='Requiere Refrigeración Después de Abierto'),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(blank=True, help_text='Ej: 12 meses, 6 meses después de abierto, etc.', max_length=100, verbose_name='Duración del Producto'),
        ),
    ]
