# Generated by Django 4.2.7 on 2026-02-02 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_general_characteristics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='general_characteristics',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packaging_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='requires_refrigeration_after_open',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shelf_life',
        ),
        migrations.CreateModel(
            name='ProductTechnicalSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Tipo de Empaque, Duración, Peso, Dimensiones, etc.', max_length=200, verbose_name='Nombre de la Característica')),
                ('description', models.CharField(help_text='Ej: Bolsa, 12 meses, 500g, 20x15x10 cm, etc.', max_length=500, verbose_name='Descripción/Valor')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor número aparece primero)', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_specs', to='store.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Especificación Técnica',
                'verbose_name_plural': 'Especificaciones Técnicas',
                'ordering': ['order', 'name'],
            },
        ),
    ]
