# Generated by Django 4.2.7 on 2026-02-03 19:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_general_characteristics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotional_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio promocional (opcional). Si se establece, este será el precio mostrado.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Promocional'),
        ),
    ]
