# Generated by Django 4.2.7 on 2026-02-03 19:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_promotional_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo de compra del producto', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo de Compra'),
        ),
    ]
