# Generated by Django 4.2.7 on 2026-02-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_purchase_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text='Selecciona de 3 a 5 productos relacionados', limit_choices_to={'available': True}, to='store.product', verbose_name='Productos Relacionados'),
        ),
    ]
