# Generated by Django 4.2.7 on 2026-02-03 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_productimage_options_productimage_is_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Ej: Garantía, Tamaño, Peso, Dimensiones, Material, etc.', max_length=100, verbose_name='Atributo')),
                ('value', models.CharField(help_text='Ej: 12 meses, Grande, 500g, 20x15x10 cm, Plástico, etc.', max_length=500, verbose_name='Valor')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor número aparece primero)', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='store.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Atributo de Producto',
                'verbose_name_plural': 'Atributos de Productos',
                'ordering': ['order', 'key'],
                'unique_together': {('product', 'key')},
            },
        ),
    ]
