# Generated by Django 4.2.7 on 2026-02-06 06:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_productattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_kind', models.CharField(choices=[('existing', 'Cliente existente'), ('natural', 'Persona natural'), ('empresa', 'Empresa')], default='existing', max_length=20, verbose_name='Tipo de cliente')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre/Razón social')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('client_phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('client_departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('client_city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('existing_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to=settings.AUTH_USER_MODEL, verbose_name='Cliente existente')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='store.product', verbose_name='Producto')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.quotation', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Item de Cotización',
                'verbose_name_plural': 'Items de Cotización',
            },
        ),
    ]
