# Generated by Django 6.0.1 on 2026-02-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_quotation_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='order_status',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('rechazado', 'Rechazado'), ('sin_respuesta', 'Sin respuesta'), ('modificado_y_enviado', 'Modificado y enviado'), ('aceptado', 'Aceptado'), ('pagado', 'Pagado')], default='sin_respuesta', max_length=30, verbose_name='Estado del pedido'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_status',
            field=models.CharField(choices=[('generada', 'Generada'), ('enviada', 'Enviada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='generada', max_length=20, verbose_name='Estado de la cotización'),
        ),
    ]
