# Generated by Django 4.2.7 on 2026-02-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_favorite_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='order_status',
            field=models.CharField(choices=[('sin_respuesta', 'Sin respuesta'), ('aceptado', 'Aceptado'), ('esperando_pago', 'Esperando pago'), ('pago_recibido', 'Pago recibido'), ('enviado', 'Enviado'), ('recibido', 'Recibido'), ('rechazado', 'Rechazado'), ('modificado_y_enviado', 'Modificado y enviado'), ('pagado', 'Pagado')], default='sin_respuesta', max_length=30, verbose_name='Estado del pedido'),
        ),
    ]
