# Generated by Django 4.2.7 on 2026-02-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_add_order_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='quotations/payment_proofs/', verbose_name='Referencia de pago'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='order_status',
            field=models.CharField(choices=[('sin_respuesta', 'Sin respuesta'), ('aceptado', 'Aceptado'), ('esperando_pago', 'Esperando pago'), ('pago_recibido', 'Pago recibido'), ('enviado', 'Enviado'), ('recibido', 'Recibido'), ('rechazado', 'Rechazado'), ('modificado_y_enviado', 'Modificado y enviado')], default='sin_respuesta', max_length=30, verbose_name='Estado del pedido'),
        ),
    ]
