# Generated by Django 6.0.1 on 2026-07-12 00:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_quotation_payment_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='DilutionBaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Opcional: notas de preparación para mostrar en la calculadora.', verbose_name='Descripción / instrucciones')),
                ('water_ml_per_base_ml', models.DecimalField(decimal_places=3, help_text='Ejemplo: proporción 1:4 → ingresa 4 (por cada 1 ml de base, 4 ml de agua).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='ML de agua por cada 1 ML de producto base')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto base (calculadora)',
                'verbose_name_plural': 'Productos base (calculadora)',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
