# Generated by Django 6.0.1 on 2026-07-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_dilution_base_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(default='ventas@mixlab.com.co', max_length=254, verbose_name='Correo de contacto')),
                ('contact_phone', models.CharField(default='+573045379501', max_length=30, verbose_name='Teléfono (visualización)')),
                ('whatsapp_number', models.CharField(default='573045379501', help_text='Ej: 573045379501 — se usa para el botón flotante y enlaces wa.me', max_length=20, verbose_name='WhatsApp (solo dígitos con código país)')),
                ('address_city', models.CharField(default='Cartagena', max_length=100, verbose_name='Ciudad')),
                ('address_country', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/mixlab_co', verbose_name='URL de Instagram')),
                ('tiktok_url', models.URLField(blank=True, default='https://www.tiktok.com/@mixlab_co', verbose_name='URL de TikTok')),
                ('facebook_url', models.URLField(blank=True, verbose_name='URL de Facebook')),
                ('promo_banner_text', models.CharField(default='Envíos gratis para Cartagena por compras superiores a $290.000', max_length=300, verbose_name='Texto del banner promocional')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
    ]
