# Generated by Django 6.0.1 on 2026-07-12 01:08

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    DilutionBaseProduct = apps.get_model('store', 'DilutionBaseProduct')
    used = set()
    for obj in DilutionBaseProduct.objects.all().order_by('id'):
        base = slugify(obj.name) or 'producto'
        slug = base
        counter = 1
        while slug in used:
            slug = f'{base}-{counter}'
            counter += 1
        used.add(slug)
        obj.slug = slug
        obj.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='dilutionbaseproduct',
            name='slug',
            field=models.SlugField(
                blank=True,
                max_length=220,
                verbose_name='Enlace para compartir',
            ),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='dilutionbaseproduct',
            name='slug',
            field=models.SlugField(
                blank=True,
                help_text='Se genera automáticamente. Ej: base-granizado → /calculadora/#base-granizado',
                max_length=220,
                unique=True,
                verbose_name='Enlace para compartir',
            ),
        ),
    ]
