# Generated by Django 4.2.7 on 2026-07-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_dilution_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Solo para identificarlo en el panel de administración.', max_length=120, verbose_name='Título (interno)')),
                ('image', models.ImageField(help_text='Proporción recomendada 3:2 (ej: 900×600 px).', upload_to='banners/sidebar/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, help_text='Descripción breve de la imagen para accesibilidad.', max_length=200, verbose_name='Texto alternativo')),
                ('link_url', models.URLField(blank=True, help_text='Si se indica, la imagen será clicable.', verbose_name='Enlace (opcional)')),
                ('open_in_new_tab', models.BooleanField(default=True, verbose_name='Abrir enlace en nueva pestaña')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner lateral',
                'verbose_name_plural': 'Banners laterales',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
