# Generated by Django 4.2.7 on 2026-07-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_sidebar_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Solo para identificarlo en el panel de administración.', max_length=120, verbose_name='Título (interno)')),
                ('image', models.ImageField(help_text='Banner ancho para la parte superior (ej: 1200×80 px o similar).', upload_to='promo-banners/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('link_url', models.URLField(blank=True, verbose_name='Enlace (opcional)')),
                ('open_in_new_tab', models.BooleanField(default=True, verbose_name='Abrir enlace en nueva pestaña')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner promocional',
                'verbose_name_plural': 'Banners promocionales',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='sidebarbanner',
            name='image',
            field=models.ImageField(help_text='Proporción 3:2. Se guarda en Supabase (bucket Mixlaba).', upload_to='banners/sidebar/', verbose_name='Imagen'),
        ),
    ]
