# Generated by Django 4.2.7 on 2026-07-15 21:25

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_mixlab_registry_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rental_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Si el arrendador lo exige, el contrato aplica el 8% del valor comercial.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Depósito / garantía (opcional)'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='image',
            field=models.ImageField(help_text='Banner ancho superior. Se guarda en Supabase (bucket Mixlaba).', upload_to='promo-banners/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='sidebarbanner',
            name='image',
            field=models.ImageField(help_text='Proporción 2:3 (ancho:alto). Se guarda en Supabase (bucket Mixlaba).', upload_to='banners/sidebar/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='promo_banner_text',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Texto del banner promocional'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(default='573128104046', help_text='Ej: 573045379501 — se usa para el botón flotante y enlaces wa.me', max_length=20, verbose_name='WhatsApp (solo dígitos con código país)'),
        ),
        migrations.CreateModel(
            name='RentalDeliveryActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre representante')),
                ('representative_signature', models.ImageField(blank=True, null=True, upload_to='quotations/delivery_acta/signatures/', verbose_name='Firma del representante')),
                ('tenant_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre arrendatario')),
                ('tenant_signature', models.ImageField(blank=True, null=True, upload_to='quotations/delivery_acta/signatures/', verbose_name='Firma del arrendatario')),
                ('photo_covers', models.ImageField(blank=True, null=True, upload_to='quotations/delivery_acta/photos/', verbose_name='Tapas y plásticos')),
                ('photo_lighting', models.ImageField(blank=True, null=True, upload_to='quotations/delivery_acta/photos/', verbose_name='Iluminación')),
                ('photo_buttons', models.ImageField(blank=True, null=True, upload_to='quotations/delivery_acta/photos/', verbose_name='Botones')),
                ('photo_radiator', models.ImageField(blank=True, null=True, upload_to='quotations/delivery_acta/photos/', verbose_name='Radiador')),
                ('photo_rear', models.ImageField(blank=True, null=True, upload_to='quotations/delivery_acta/photos/', verbose_name='Parte trasera')),
                ('photo_front', models.ImageField(blank=True, null=True, upload_to='quotations/delivery_acta/photos/', verbose_name='Parte delantera')),
                ('delivery_notes', models.TextField(blank=True, default='', verbose_name='Observaciones de entrega')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_acta', to='store.quotation', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Acta de recepción de alquiler',
                'verbose_name_plural': 'Actas de recepción de alquiler',
            },
        ),
        migrations.CreateModel(
            name='RentalContractRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre representante')),
                ('representative_signature', models.ImageField(blank=True, null=True, upload_to='quotations/rental_requirements/signatures/', verbose_name='Firma del representante')),
                ('tenant_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre arrendatario')),
                ('tenant_signature', models.ImageField(blank=True, null=True, upload_to='quotations/rental_requirements/signatures/', verbose_name='Firma del arrendatario')),
                ('id_front', models.ImageField(blank=True, null=True, upload_to='quotations/rental_requirements/ids/', verbose_name='Cédula (frente)')),
                ('id_back', models.ImageField(blank=True, null=True, upload_to='quotations/rental_requirements/ids/', verbose_name='Cédula (reverso)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requirements', to='store.quotation', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Requisitos de contrato de alquiler',
                'verbose_name_plural': 'Requisitos de contratos de alquiler',
            },
        ),
    ]
