# Generated by Django 4.2.7 on 2026-07-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_wa_n8n_and_finance_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='order_status',
            field=models.CharField(choices=[('sin_respuesta', 'Sin respuesta'), ('aceptado', 'Aceptado'), ('esperando_pago', 'Esperando pago'), ('pago_parcial', 'Pago parcial'), ('pago_recibido', 'Pago recibido'), ('enviado', 'Enviado'), ('recibido', 'Recibido'), ('rechazado', 'Rechazado'), ('modificado_y_enviado', 'Modificado y enviado')], default='sin_respuesta', max_length=30, verbose_name='Estado del pedido'),
        ),
    ]
