# Generated by Django 4.2.7 on 2026-07-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_quotation_pago_parcial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='quotation_status',
            field=models.CharField(choices=[('generada', 'Generada'), ('enviada', 'Enviada'), ('cerrada', 'Cerrada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='generada', max_length=20, verbose_name='Estado de la cotización'),
        ),
    ]
