# Generated by Django 5.2.16 on 2026-07-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_quotation_status_cerrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='client_document',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Número de cédula / documento'),
        ),
    ]
