# Generated by Django 5.2.16 on 2026-07-27 04:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_rentalcombo_slug_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='custom_name',
            field=models.CharField(blank=True, default='', help_text='Para extras o el paquete combo sin producto de inventario.', max_length=200, verbose_name='Nombre personalizado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('sale', 'Venta'), ('rental', 'Alquiler')], default='sale', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Vacío si es un extra / línea personalizada (p. ej. combo o complemento).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='store.product', verbose_name='Producto'),
        ),
        migrations.CreateModel(
            name='ComboBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_kind', models.CharField(choices=[('existing', 'Cliente existente'), ('natural', 'Persona natural'), ('empresa', 'Empresa')], default='natural', max_length=20, verbose_name='Tipo de cliente')),
                ('client_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre / razón social')),
                ('client_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo')),
                ('client_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono')),
                ('client_document', models.CharField(blank=True, default='', max_length=30, verbose_name='Documento')),
                ('client_departamento', models.CharField(blank=True, default='', max_length=100, verbose_name='Departamento')),
                ('client_city', models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad')),
                ('event_date', models.DateField(verbose_name='Fecha del evento')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='Hora del evento')),
                ('location_text', models.CharField(blank=True, default='', max_length=500, verbose_name='Dirección / ubicación')),
                ('maps_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Enlace Google Maps')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud')),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio del paquete cobrado')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='agendado', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='store.rentalcombo', verbose_name='Combo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_bookings_created', to=settings.AUTH_USER_MODEL, verbose_name='Agendado por')),
                ('existing_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Cliente existente')),
                ('quotation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_booking', to='store.quotation', verbose_name='Cotización generada')),
            ],
            options={
                'verbose_name': 'Agenda de combo',
                'verbose_name_plural': 'Agendas de combos',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComboBookingExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre del extra')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio unitario')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Notas')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='store.combobooking', verbose_name='Agenda')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_booking_extras', to='store.category', verbose_name='Categoría')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_booking_extras', to='store.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Extra de agenda',
                'verbose_name_plural': 'Extras de agenda',
                'ordering': ['order', 'id'],
            },
        ),
    ]
