# Generated by Django 5.2.16 on 2026-07-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_combo_booking_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcomboitem',
            name='is_modifiable',
            field=models.BooleanField(default=False, help_text='Si está activo, al agendar se puede cambiar cantidad, producto/tipo y valor. Si está apagado, el elemento es obligatorio y queda fijo.', verbose_name='Modificable al agendar'),
        ),
    ]
