# Generated by Django 5.2.16 on 2026-07-27 05:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def forwards_migrate_legacy_payments(apps, schema_editor):
    Quotation = apps.get_model('store', 'Quotation')
    QuotationPayment = apps.get_model('store', 'QuotationPayment')
    for q in Quotation.objects.all().iterator():
        if QuotationPayment.objects.filter(quotation_id=q.id).exists():
            continue
        has_proof = bool(q.payment_proof)
        amount = q.partial_payment_amount
        if amount is None or amount <= 0:
            if q.order_status in ('pago_recibido', 'enviado', 'recibido', 'modificado_y_enviado'):
                amount = q.total or Decimal('0.00')
            else:
                amount = None
        if not has_proof and (amount is None or amount <= 0):
            continue
        if amount is None or amount <= 0:
            amount = Decimal('0.01')
        pay_type = 'total' if q.order_status in (
            'pago_recibido', 'enviado', 'recibido', 'modificado_y_enviado'
        ) else 'parcial'
        pay = QuotationPayment(
            quotation_id=q.id,
            payment_type=pay_type,
            amount=amount,
            notes='Migrado desde registro anterior',
            created_by_id=q.created_by_id,
        )
        if has_proof:
            pay.proof.name = q.payment_proof.name
        pay.save()
        if q.updated_at:
            QuotationPayment.objects.filter(pk=pay.pk).update(created_at=q.updated_at)


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_combo_item_is_modifiable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('parcial', 'Parcial'), ('total', 'Total')], default='parcial', max_length=20, verbose_name='Tipo de pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('proof', models.ImageField(upload_to='quotations/payment_proofs/', verbose_name='Comprobante')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_payments', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='store.quotation', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Pago de cotización',
                'verbose_name_plural': 'Pagos de cotización',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.RunPython(forwards_migrate_legacy_payments, backwards_noop),
    ]
