# Generated by Django 5.2.16 on 2026-08-11 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_quotation_payment_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLandingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_name', models.CharField(max_length=200, verbose_name='Nombre del organizador')),
                ('event_type', models.CharField(choices=[('boda', 'Boda'), ('cumpleanos', 'Cumpleaños'), ('corporativo', 'Evento corporativo'), ('graduacion', 'Graduación'), ('quince', 'Quinceaños'), ('baby_shower', 'Baby shower'), ('feria', 'Feria / activación'), ('otro', 'Otro')], max_length=40, verbose_name='Tipo de evento')),
                ('event_date', models.DateField(verbose_name='Fecha del evento')),
                ('guests_count', models.PositiveIntegerField(verbose_name='Número de invitados')),
                ('phone', models.CharField(max_length=40, verbose_name='WhatsApp / teléfono')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas del cliente')),
                ('source', models.CharField(blank=True, default='landing_eventos', max_length=80, verbose_name='Origen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_leads', to='store.rentalcombo', verbose_name='Combo')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_landing_leads', to='store.quotation', verbose_name='Cotización generada')),
            ],
            options={
                'verbose_name': 'Lead landing eventos',
                'verbose_name_plural': 'Leads landing eventos',
                'ordering': ['-created_at'],
            },
        ),
    ]
