# Generated by Django 5.2.16 on 2026-08-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_event_landing_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlandinglead',
            name='event_place',
            field=models.CharField(default='', help_text='Salón, dirección o sitio donde se realizará el evento.', max_length=255, verbose_name='Lugar del evento'),
        ),
        migrations.AlterField(
            model_name='eventlandinglead',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Ciudad'),
        ),
    ]
