# Generated by Django 5.2.16 on 2026-08-11 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_event_lead_city_place_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlandinglead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead de evento', 'verbose_name_plural': 'Leads de eventos'},
        ),
        migrations.AddField(
            model_name='eventlandinglead',
            name='staff_notes',
            field=models.TextField(blank=True, default='', verbose_name='Notas internas del asesor'),
        ),
        migrations.AddField(
            model_name='eventlandinglead',
            name='status',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('cotizado', 'Cotizado'), ('ganado', 'Ganado'), ('perdido', 'Perdido')], default='nuevo', max_length=20, verbose_name='Estado del lead'),
        ),
        migrations.AddField(
            model_name='eventlandinglead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventlandinglead',
            name='city',
            field=models.CharField(default='Cartagena', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='eventlandinglead',
            name='quotation',
            field=models.ForeignKey(blank=True, help_text='Opcional. Se vincula después, cuando el asesor arma la cotización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_landing_leads', to='store.quotation', verbose_name='Cotización (si el asesor la creó)'),
        ),
    ]
