# Generated by Django 5.2.16 on 2026-08-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_event_lead_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationpayment',
            name='method',
            field=models.CharField(choices=[('transferencia', 'Transferencia / comprobante'), ('efectivo', 'Efectivo')], default='transferencia', max_length=20, verbose_name='Medio de pago'),
        ),
        migrations.AlterField(
            model_name='quotationpayment',
            name='proof',
            field=models.ImageField(blank=True, help_text='Obligatorio para transferencia. No aplica en efectivo.', null=True, upload_to='quotations/payment_proofs/', verbose_name='Comprobante'),
        ),
    ]
