# Generated by Django 5.2.16 on 2026-08-31 23:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_sitesettings_not_grand_contributor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DianInvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='SETP', max_length=10, verbose_name='Prefijo')),
                ('range_from', models.PositiveBigIntegerField(default=990000000, verbose_name='Desde')),
                ('range_to', models.PositiveBigIntegerField(default=995000000, verbose_name='Hasta')),
                ('current', models.PositiveBigIntegerField(default=989999999, verbose_name='Último consecutivo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Numeración DIAN',
                'verbose_name_plural': 'Numeración DIAN',
            },
        ),
        migrations.CreateModel(
            name='DianElectronicInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, verbose_name='Prefijo')),
                ('consecutive', models.PositiveBigIntegerField(verbose_name='Consecutivo')),
                ('invoice_number', models.CharField(max_length=30, unique=True, verbose_name='Número de factura')),
                ('environment', models.CharField(default='HABILITACION', max_length=20, verbose_name='Ambiente')),
                ('issue_date', models.DateField(verbose_name='Fecha emisión')),
                ('issue_time', models.TimeField(verbose_name='Hora emisión')),
                ('cufe', models.CharField(blank=True, default='', max_length=96, verbose_name='CUFE')),
                ('qr_url', models.URLField(blank=True, default='', max_length=500, verbose_name='URL QR')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('iva_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('xml_unsigned', models.TextField(blank=True, default='', verbose_name='XML sin firmar')),
                ('xml_signed', models.FileField(blank=True, null=True, upload_to='dian/invoices/xml/', verbose_name='XML firmado')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='dian/invoices/pdf/', verbose_name='PDF representación gráfica')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('xml_generated', 'XML generado'), ('signed', 'Firmado'), ('submitted', 'Enviado a DIAN'), ('accepted', 'Aceptado DIAN'), ('rejected', 'Rechazado DIAN'), ('error', 'Error')], default='draft', max_length=20)),
                ('dian_track_id', models.CharField(blank=True, default='', max_length=120, verbose_name='Track ID DIAN')),
                ('dian_status_code', models.CharField(blank=True, default='', max_length=20)),
                ('dian_status_message', models.TextField(blank=True, default='')),
                ('dian_response_raw', models.TextField(blank=True, default='')),
                ('software_id', models.CharField(blank=True, default='', max_length=120)),
                ('technical_key', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dian_invoices_emitted', to=settings.AUTH_USER_MODEL, verbose_name='Emitida por')),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dian_invoice', to='store.quotation', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Factura electrónica DIAN',
                'verbose_name_plural': 'Facturas electrónicas DIAN',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DianSubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60, verbose_name='Acción')),
                ('request_summary', models.TextField(blank=True, default='')),
                ('response_summary', models.TextField(blank=True, default='')),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_logs', to='store.dianelectronicinvoice', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Log envío DIAN',
                'verbose_name_plural': 'Logs envío DIAN',
                'ordering': ['-created_at'],
            },
        ),
    ]
