# Generated by Django 5.2.16 on 2026-09-01 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_dian_electronic_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DianHabilitacionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_set_id', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('generated', 'Generado'), ('signed', 'Firmado'), ('zipped', 'ZIP listo'), ('submitted', 'Enviado DIAN'), ('accepted', 'Aceptado DIAN'), ('rejected', 'Rechazado'), ('error', 'Error')], default='draft', max_length=20)),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='dian/habilitacion/zips/')),
                ('dian_track_id', models.CharField(blank=True, default='', max_length=120)),
                ('dian_response', models.TextField(blank=True, default='')),
                ('invoice_count', models.PositiveSmallIntegerField(default=0)),
                ('credit_note_count', models.PositiveSmallIntegerField(default=0)),
                ('debit_note_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lote habilitación DIAN',
                'verbose_name_plural': 'Lotes habilitación DIAN',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DianHabilitacionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('invoice', 'Factura'), ('credit_note', 'Nota crédito'), ('debit_note', 'Nota débito')], max_length=20)),
                ('document_number', models.CharField(max_length=30)),
                ('consecutive', models.PositiveBigIntegerField()),
                ('cufe_cude', models.CharField(blank=True, default='', max_length=96)),
                ('reference_number', models.CharField(blank=True, default='', max_length=30)),
                ('reference_cufe', models.CharField(blank=True, default='', max_length=96)),
                ('xml_unsigned', models.TextField(blank=True, default='')),
                ('xml_signed', models.FileField(blank=True, null=True, upload_to='dian/habilitacion/xml/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='store.dianhabilitacionbatch')),
            ],
            options={
                'verbose_name': 'Documento habilitación',
                'verbose_name_plural': 'Documentos habilitación',
                'ordering': ['consecutive'],
                'unique_together': {('batch', 'document_number')},
            },
        ),
    ]
