# Generated by Django 4.2.7 on 2026-01-16 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('duration_type', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], max_length=20, verbose_name='Tipo de duración')),
                ('duration_quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad de duración')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio diario')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio total')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Nombre de contacto')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('delivery_address', models.TextField(verbose_name='Dirección de entrega')),
                ('delivery_city', models.CharField(max_length=100, verbose_name='Ciudad de entrega')),
                ('special_requirements', models.TextField(blank=True, verbose_name='Requisitos especiales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='store.product', verbose_name='Producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Alquiler',
                'verbose_name_plural': 'Alquileres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='store.product', verbose_name='Producto')),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_dates', to='rentals.rental', verbose_name='Alquiler')),
            ],
            options={
                'verbose_name': 'Disponibilidad de Alquiler',
                'verbose_name_plural': 'Disponibilidades de Alquiler',
                'ordering': ['date'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
