# Generated by Django 6.0.1 on 2026-09-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='duration_type',
            field=models.CharField(choices=[('hourly', 'Por hora'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], max_length=20, verbose_name='Tipo de duración'),
        ),
    ]
