# Generated by Django 4.2.7 on 2026-02-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_address_remove_userprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='departamento',
            field=models.CharField(default='', max_length=100, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='google_maps_ubicacion',
            field=models.URLField(blank=True, help_text='Pega el enlace de Google Maps de la ubicación', max_length=500, verbose_name='Ubicación en Google Maps'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='punto_referencia',
            field=models.CharField(blank=True, help_text='Ej: Frente al parque, diagonal a la panadería', max_length=255, verbose_name='Punto de referencia'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.TextField(verbose_name='Dirección exacta'),
        ),
    ]
