# Generated by Django 4.2.7 on 2026-02-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shipping_address_dpa_colombia'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='client_type',
            field=models.CharField(blank=True, choices=[('natural', 'Persona natural'), ('empresa', 'Empresa')], default='natural', max_length=20, verbose_name='Tipo de cliente'),
        ),
    ]
