# Generated by Django 4.2.7 on 2026-02-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_client_type_and_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Departamento'),
        ),
    ]
