# Generated by Django 5.2.16 on 2026-07-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_profile_departamento_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='document_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Número de cédula / documento'),
        ),
    ]
